name:                memoman
version:             0.1.0.0
github:              "AyeGill/memoman"
license:             BSD3
author:              "Eigil Fjeldgren Rischel"
maintainer:          "ayegill@gmail.com"
copyright:           "2019 Eigil Fjeldgren Rischel"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/ayegill/memoman#readme>

dependencies:
- base >= 4.7 && < 5
- time >= 1.8.0 
- bytestring >= 0.10
- uuid >= 1.0
- data-ordlist >= 0.4
- cereal >= 0.5.8
- cereal-time >= 0.1
- text >= 1.2.3
- shelly >= 1.8

library:
  source-dirs: src

executables:
  memoman-cli:
    main:                Main.hs
    source-dirs:         cli-app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - memoman
  
  memoman-gui:
    main:                Main.hs
    source-dirs:         gui-app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - memoman

tests:
  memoman-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - memoman
    - QuickCheck >= 2
    - quickcheck-instances (>= 0.3 && < 0.3.21)
